# application.yml for Eureka Server
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: service-registry
  cloud:
    config:
      import-check-enabled: false
